[[timg]]
arch = "x86_64"
git-tree-sha1 = "46b9ed49369a7ff19252ff6951ab8e15e3851ec8"
libc = "glibc"
os = "linux"

    [[timg.download]]
    sha256 = "8f92dc5a42ab6a3cfd6f851b013ce72dd8b54ef882797f51eeaf9364b33575da"
    url = "https://github.com/Moelf/timg_jll.jl/releases/download/timg-v1.4.2+0/timg.v1.4.2.x86_64-linux-gnu.tar.gz"
