# Autogenerated wrapper script for timg_jll for x86_64-linux-gnu
export timg

using Zlib_jll
using FFMPEG_jll
using JpegTurbo_jll
using libexif_jll
using OpenSlide_jll
using libgraphicsmagic_jll
JLLWrappers.@generate_wrapper_header("timg")
JLLWrappers.@declare_executable_product(timg)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, FFMPEG_jll, JpegTurbo_jll, libexif_jll, OpenSlide_jll, libgraphicsmagic_jll)
    JLLWrappers.@init_executable_product(
        timg,
        "bin/timg",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
